#!/bin/sh

fichier=$(basename "$1" ".asm") 
echo '###########################'
echo 'suppression du fichier ' $fichier.bin
rm $fichier.bin
echo 'suppresion du fichier ' $fichier.sym
rm $fichier.sym
echo 'compilation et execution du fichier ' $fichier.asm
dasm $1 -f3 -o$fichier.bin -s$fichier.sym &&  stella $fichier.bin
echo '###########################'
exit 0
